version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  web:
    build: .
    command: bash -c "npm start && npm run build:db"
    image: shipping-billing-component
    ports:
      - "8565:8565"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db
