version: '3'
services:
  web:
    build: .
    restart: always
    environment:
      DATABASE_URL: postgres://postgres@db/auction
    depends_on:
      - db
    ports:
      - "9000:9000"
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: auction
