const productSeeds = [
  {
    name:
      'Eachine E58 2MP 720P Camera WIFI FPV Foldable Drone 2.4G 6-Axis RC Quadcopter',
    condition: 'New',
    minimum: 10,
    watchers: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'EVGA Graphics Card',
    condition: 'New',
    minimum: 20,
    watchers: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Massager',
    condition: 'New',
    minimum: 12,
    watchers: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Cookware',
    condition: 'New',
    minimum: 20,
    watchers: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Treadmill Sheets',
    condition: 'New',
    minimum: 40,
    watchers: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Apple Mouse',
    condition: 'New',
    minimum: 10,
    watchers: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'iPhone 6',
    condition: 'New',
    minimum: 20,
    watchers: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'iPhone 7',
    condition: 'New',
    minimum: 30,
    watchers: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'iPhone X',
    condition: 'New',
    minimum: 40,
    watchers: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Whiteboards',
    condition: 'New',
    minimum: 50,
    watchers: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Pens',
    condition: 'New',
    minimum: 10,
    watchers: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'North Face Backpack',
    condition: 'New',
    minimum: 10,
    watchers: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Apple Earbuds',
    condition: 'New',
    minimum: 40,
    watchers: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Expo Markers',
    condition: 'New',
    minimum: 40,
    watchers: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Hand-Crafted Desk',
    condition: 'New',
    minimum: 40,
    watchers: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Recliner',
    condition: 'New',
    minimum: 40,
    watchers: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Large Umbrella',
    condition: 'New',
    minimum: 50,
    watchers: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Macbook Pro',
    condition: 'New',
    minimum: 50,
    watchers: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Macbook Air',
    condition: 'New',
    minimum: 50,
    watchers: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Tires',
    condition: 'New',
    minimum: 50,
    watchers: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: '2011 Honda Accord',
    condition: 'New',
    minimum: 50,
    watchers: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Black Sweater',
    condition: 'New',
    minimum: 50,
    watchers: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'HydroFlask',
    condition: 'New',
    minimum: 20,
    watchers: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Pack of 5 Peanuts',
    condition: 'New',
    minimum: 20,
    watchers: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Jean Jacket',
    condition: 'New',
    minimum: 20,
    watchers: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Apple Earbud Convertew',
    condition: 'New',
    minimum: 30,
    watchers: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Gmail Account',
    condition: 'New',
    minimum: 40,
    watchers: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Drone',
    condition: 'New',
    minimum: 20,
    watchers: 9,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Box of Pizza',
    condition: 'New',
    minimum: 5,
    watchers: 9,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Apple Macbook Charger',
    condition: 'New',
    minimum: 15,
    watchers: 9,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'HP Spectre Laptop',
    condition: 'New',
    minimum: 13,
    watchers: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Juice',
    condition: 'New',
    minimum: 15,
    watchers: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Prescription Glasses',
    condition: 'New',
    minimum: 60,
    watchers: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Baseball Cap',
    condition: 'New',
    minimum: 60,
    watchers: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Dog Toys and Treats',
    condition: 'New',
    minimum: 23,
    watchers: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Amazon Key Home Kit',
    condition: 'New',
    minimum: 53,
    watchers: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Kitchen Sink Strainer',
    condition: 'New',
    minimum: 56,
    watchers: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Echo Dot',
    condition: 'New',
    minimum: 34,
    watchers: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Bike Seat Cover',
    condition: 'New',
    minimum: 20,
    watchers: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Magnetic Phone Car Mount',
    condition: 'New',
    minimum: 20,
    watchers: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'iPhone Cable',
    condition: 'New',
    minimum: 20,
    watchers: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Rankie Micro USB',
    condition: 'Like New',
    minimum: 20,
    watchers: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Dishwasher Detergent',
    condition: 'Like New',
    minimum: 20,
    watchers: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'High Potency Biotin',
    condition: 'Like New',
    minimum: 20,
    watchers: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Fiji Water',
    condition: 'Like New',
    minimum: 20,
    watchers: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: '50ft Garden Hose',
    condition: 'Like New',
    minimum: 20,
    watchers: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Lightning Cable Charger',
    condition: 'Like New',
    minimum: 20,
    watchers: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Bluetooth Headphones',
    condition: 'Like New',
    minimum: 20,
    watchers: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Amazon Tap',
    condition: 'Like New',
    minimum: 40,
    watchers: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Meat Thermometer',
    condition: 'Like New',
    minimum: 40,
    watchers: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Cell Phone Stand',
    condition: 'Like New',
    minimum: 40,
    watchers: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Echo Spot',
    condition: 'Like New',
    minimum: 40,
    watchers: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Power Strip Tower',
    condition: 'Like New',
    minimum: 40,
    watchers: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Power Strip',
    condition: 'Like New',
    minimum: 40,
    watchers: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Mens Shoes',
    condition: 'Like New',
    minimum: 40,
    watchers: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'LaserGrip',
    condition: 'Like New',
    minimum: 40,
    watchers: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Lavender Oil',
    condition: 'Like New',
    minimum: 10,
    watchers: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Colgate Dash Button',
    condition: 'Like New',
    minimum: 10,
    watchers: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Skiing Lesson',
    condition: 'Like New',
    minimum: 10,
    watchers: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Karate Lesson',
    condition: 'Like New',
    minimum: 10,
    watchers: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Piano Lesson',
    condition: 'Like New',
    minimum: 10,
    watchers: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Guitar Lesson',
    condition: 'Like New',
    minimum: 10,
    watchers: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Brush Pens',
    condition: 'Good',
    minimum: 30,
    watchers: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Kindle',
    condition: 'Good',
    minimum: 50,
    watchers: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Running Belt',
    condition: 'Good',
    minimum: 10,
    watchers: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Running Shoes',
    condition: 'Good',
    minimum: 10,
    watchers: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Plants',
    condition: 'Good',
    minimum: 10,
    watchers: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Office Space',
    condition: 'Good',
    minimum: 10,
    watchers: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Shopping Bag',
    condition: 'Good',
    minimum: 10,
    watchers: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Cardboard',
    condition: 'Good',
    minimum: 10,
    watchers: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Vitamins',
    condition: 'Good',
    minimum: 10,
    watchers: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Dirt Bike',
    condition: 'Good',
    minimum: 10,
    watchers: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Dirt',
    condition: 'Good',
    minimum: 10,
    watchers: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'License Plate',
    condition: 'Good',
    minimum: 10,
    watchers: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Stop Sign',
    condition: 'Good',
    minimum: 10,
    watchers: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Vintage Baseball Cards',
    condition: 'Good',
    minimum: 10,
    watchers: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Magic the Gathering Cards',
    condition: 'Good',
    minimum: 10,
    watchers: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Sony TV',
    condition: 'Good',
    minimum: 10,
    watchers: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: '4k Monitor',
    condition: 'Good',
    minimum: 11,
    watchers: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Trip to the Zoo',
    condition: 'Good',
    minimum: 11,
    watchers: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'DisneyLand Tickets',
    condition: 'Good',
    minimum: 20,
    watchers: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Photo of Me',
    condition: 'Good',
    minimum: 20,
    watchers: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Photo of You',
    condition: 'Good',
    minimum: 20,
    watchers: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Wedding DJ',
    condition: 'Good',
    minimum: 20,
    watchers: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Door',
    condition: 'Good',
    minimum: 20,
    watchers: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Figurines',
    condition: 'Good',
    minimum: 20,
    watchers: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'New Skates',
    condition: 'Poor',
    minimum: 10,
    watchers: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Black Suit',
    condition: 'Poor',
    minimum: 20,
    watchers: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Boots',
    condition: 'Poor',
    minimum: 30,
    watchers: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Canteen',
    condition: 'Poor',
    minimum: 30,
    watchers: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'LOTR DVD Set',
    condition: 'Poor',
    minimum: 30,
    watchers: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'A Real Product',
    condition: 'Poor',
    minimum: 30,
    watchers: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'PS4',
    condition: 'Poor',
    minimum: 30,
    watchers: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'DualShock Controller',
    condition: 'Poor',
    minimum: 30,
    watchers: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Video Games',
    condition: 'Poor',
    minimum: 30,
    watchers: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'YouTube Account',
    condition: 'Poor',
    minimum: 30,
    watchers: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'One Rib',
    condition: 'Poor',
    minimum: 50,
    watchers: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'iPhone Case',
    condition: 'Poor',
    minimum: 10,
    watchers: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Trash',
    condition: 'Poor',
    minimum: 15,
    watchers: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Trash Can',
    condition: 'Poor',
    minimum: 16,
    watchers: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

const bidSeeds = [
  { productId: 1, amount: 140.0, createdAt: new Date(), updatedAt: new Date() },
  { productId: 2, amount: 140.0, createdAt: new Date(), updatedAt: new Date() },
  { productId: 3, amount: 140.0, createdAt: new Date(), updatedAt: new Date() },
  { productId: 4, amount: 140.0, createdAt: new Date(), updatedAt: new Date() },
  { productId: 5, amount: 140.0, createdAt: new Date(), updatedAt: new Date() },
  { productId: 6, amount: 140.0, createdAt: new Date(), updatedAt: new Date() },
  { productId: 7, amount: 140.0, createdAt: new Date(), updatedAt: new Date() },
  { productId: 8, amount: 140.0, createdAt: new Date(), updatedAt: new Date() },
  { productId: 9, amount: 140.0, createdAt: new Date(), updatedAt: new Date() },
  {
    productId: 10,
    amount: 310.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 11,
    amount: 310.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 12,
    amount: 310.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 13,
    amount: 310.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 14,
    amount: 310.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 15,
    amount: 310.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 16,
    amount: 310.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 17,
    amount: 310.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 18,
    amount: 310.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 19,
    amount: 310.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 20,
    amount: 310.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 21,
    amount: 160.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 22,
    amount: 160.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 23,
    amount: 160.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 24,
    amount: 160.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 25,
    amount: 160.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 26,
    amount: 160.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 27,
    amount: 160.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 28,
    amount: 160.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 29,
    amount: 160.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 30,
    amount: 160.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 31,
    amount: 160.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 32,
    amount: 130.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 33,
    amount: 130.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 34,
    amount: 130.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 35,
    amount: 130.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 36,
    amount: 130.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 37,
    amount: 130.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 38,
    amount: 130.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 39,
    amount: 130.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 40,
    amount: 130.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 41,
    amount: 130.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 42,
    amount: 130.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 43,
    amount: 800.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 44,
    amount: 800.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 45,
    amount: 800.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 46,
    amount: 800.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 47,
    amount: 800.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 48,
    amount: 800.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 49,
    amount: 800.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 50,
    amount: 800.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 51,
    amount: 800.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 52,
    amount: 800.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 53,
    amount: 800.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 54,
    amount: 320.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 55,
    amount: 320.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 56,
    amount: 320.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 57,
    amount: 320.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 58,
    amount: 320.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 59,
    amount: 320.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 60,
    amount: 320.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 61,
    amount: 320.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 62,
    amount: 320.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 63,
    amount: 320.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 64,
    amount: 320.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 65,
    amount: 812.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 66,
    amount: 812.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 67,
    amount: 812.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 68,
    amount: 812.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 69,
    amount: 812.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 70,
    amount: 812.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 71,
    amount: 812.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 72,
    amount: 812.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 73,
    amount: 812.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 74,
    amount: 812.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 75,
    amount: 812.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 76,
    amount: 210.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 77,
    amount: 210.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 78,
    amount: 210.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 79,
    amount: 210.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 80,
    amount: 210.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 81,
    amount: 210.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 82,
    amount: 210.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 83,
    amount: 210.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 84,
    amount: 210.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 85,
    amount: 210.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 86,
    amount: 210.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 87,
    amount: 123.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 88,
    amount: 123.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 89,
    amount: 123.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 90,
    amount: 123.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 91,
    amount: 123.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 92,
    amount: 123.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 93,
    amount: 123.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 94,
    amount: 123.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 95,
    amount: 123.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 96,
    amount: 123.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 97,
    amount: 123.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 98,
    amount: 123.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 99,
    amount: 345.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 100,
    amount: 123.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

module.exports = {
  productSeeds,
  bidSeeds,
};
